GET http://localhost:5014/games

###
GET http://localhost:5014/games/1

###
POST http://localhost:5014/games
Content-Type: application/json

{
"name":"FC24",
    "genreId":3,
    "price":25.33,
    "releaseDate":"2011-11-18"
}

###
PUT  http://localhost:5014/games/1
Content-Type: application/json

{
    "name":"minecraft",
    "genreId":5,
    "price":25.33,
    "releaseDate":"2011-11-18"
}

###
DELETE http://localhost:5014/games/1